Remove scripts, it makes OpenGrok unhappy
Error log:
20:34:54 WARNING: An error occured while creating cache for /var/opengrok/src/scripts (SubversionRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get path relative to source root for /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/remote-fs.target
        at org.opensolaris.opengrok.history.FileHistoryCache.getCachedFile(FileHistoryCache.java:190)
        at org.opensolaris.opengrok.history.FileHistoryCache.storeFile(FileHistoryCache.java:221)
        at org.opensolaris.opengrok.history.FileHistoryCache.doFileHistory(FileHistoryCache.java:127)
        at org.opensolaris.opengrok.history.FileHistoryCache.store(FileHistoryCache.java:399)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:328)
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:496)
        at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:54)
        at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:546)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Failed to resolve [/lib/systemd/system/remote-fs.target] relative to source root [/var/opengrok/src]
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getPathRelativeToSourceRoot(RuntimeEnvironment.java:292)
        at org.opensolaris.opengrok.history.FileHistoryCache.getCachedFile(FileHistoryCache.java:183)
        ... 12 more
20:34:56 WARNING: Warning: could not read /var/opengrok/src/scripts-pony/web_scripts/.htaccess.mit
20:35:14 WARNING: Warning: could not read /var/opengrok/src/scripts/locker/doc/object-identifiers
20:35:58 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/munin/plugins/apache_accesses
20:35:58 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/munin/plugins/apache_processes
20:35:58 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/munin/plugins/apache_volume
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/basic.target.wants/ip6tables.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/basic.target.wants/iptables.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/afs-000.mount
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/crond.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/ntpd.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/openafs-client.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/scripts-afsagent-startup.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/scripts-afsagent.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/scripts-afsagent.timer
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/scripts-whoisd.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/syslog-ng.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/var-lib-mock.service
20:36:21 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/etc/systemd/system/multi-user.target.wants/yum-updatesd.service
20:36:23 WARNING: Warning: could not read /var/opengrok/src/scripts/server/fedora/config/usr/vice/etc/NetRestrict